"""The official Pokédex heights and weights in metric units.

The European and Japanese carts print a Pokémon's height in metres and its
weight in kilograms; the US Generation 1 and 2 carts store and print feet,
inches and pounds instead, and gen1recomp reads the US cart.  pret's
pokeemerald keeps every species' official metric values (decimetres and
hectograms, ``src/data/pokemon/pokedex_entries.h``), pinned under
``[pret.pokedex_metrics]`` in ``config/pipeline.toml``.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Iterable, Mapping

from .builder import BuildError
from .dependencies import DependencyError, fetch_files

POKEDEX_ENTRIES_FILE = "pokedex_entries.h"

_ENTRY = re.compile(r"\[NATIONAL_DEX_(\w+)\]\s*=\s*\{(.*?)\n\s*\}", re.S)
_FIELD = re.compile(r"\.(height|weight)\s*=\s*(\d+)")


def prepare_pokedex_metrics(workspace: str | Path, config: Mapping) -> Path:
    """Download the pinned pokeemerald Pokédex entries."""
    section = (config.get("pret") or {}).get("pokedex_metrics") or {}
    try:
        folder = fetch_files(
            str(section["archive_base_url"]), dict(section["archive_files"]),
            Path(workspace) / "dependencies" / "pret" / "pokedex_metrics",
            revision=str(section.get("revision", "")),
        )
    except (DependencyError, KeyError, TypeError, ValueError, OSError) as error:
        raise BuildError(f"Unable to download pinned pret pokedex_metrics: {error}") from error
    return folder / POKEDEX_ENTRIES_FILE


def parse_pokedex_metrics(text: str) -> dict[str, tuple[int, int]]:
    """Each species' height in decimetres and weight in hectograms, by its
    ``NATIONAL_DEX_*`` name (``BULBASAUR``, ``NIDORAN_F``, ``MR_MIME``)."""
    out: dict[str, tuple[int, int]] = {}
    for name, body in _ENTRY.findall(text):
        fields = dict(_FIELD.findall(body))
        if name == "NONE" or "height" not in fields or "weight" not in fields:
            continue
        out[name] = (int(fields["height"]), int(fields["weight"]))
    return out


def species_metrics(path: str | Path, species_ids: Iterable[str]) -> dict[str, tuple[float, float]]:
    """``{species id: (metres, kilograms)}`` for the given engine ids, which
    are pret's species constants, the same names as ``NATIONAL_DEX_*``."""
    metrics = parse_pokedex_metrics(Path(path).read_text(encoding="utf-8"))
    out: dict[str, tuple[float, float]] = {}
    missing = []
    for species in species_ids:
        value = metrics.get(species)
        if value is None:
            missing.append(species)
            continue
        out[species] = (value[0] / 10, value[1] / 10)
    if missing:
        raise BuildError("no official metric height and weight for: " + ", ".join(sorted(missing)))
    return out


def lua_catalog(values: Mapping[str, tuple[float, float]], title: str) -> str:
    """A ``lang/species_metrics.lua`` catalog: ``{metres, kilograms}`` by id."""
    lines = [f"-- Generated by multilingual pipeline: {title}", "return {"]
    for species in sorted(values):
        metres, kilograms = values[species]
        lines.append(f'  ["{species}"] = {{ {metres:g}, {kilograms:g} }},')
    lines.append("}")
    return "\n".join(lines) + "\n"
