"""Engine ``strings.lua`` catalogue integration.

The modkit engine catalogue is keyed by the English source text.  It is kept
separate from the ROM worksheets because it is not a ROM export.
"""
from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass
import ast
import json
from pathlib import Path
import re
from typing import Iterable, Mapping

from .model import Alignment, CorpusRecord
from .tokens import DYNAMIC_TOKEN_RE, corpus_to_engine

ENGINE_SCHEMA = "gen1recomp-translation-mods/engine-overrides"
ANCHOR_SCHEMA = "gen1recomp-translation-mods/semantic-anchors"
ROM_CATALOGS = ("dialogue", "species_names", "move_names", "item_names", "trainer_names", "status_labels")


@dataclass(frozen=True)
class EngineEntry:
    source: str


def _lua_unquote(value: str) -> str:
    # strings.lua generated by modkit uses ordinary Lua quoted strings.
    value = value[1:-1]
    return bytes(value, "utf-8").decode("unicode_escape").encode("latin1", "backslashreplace").decode("latin1") if "\\" in value else value


def read_engine_catalog(path: str | Path) -> dict[str, str]:
    """Read a generated strings.lua, rejecting malformed/non-empty entries."""
    path = Path(path)
    if not path.is_file():
        raise FileNotFoundError(f"engine strings catalogue missing: {path}")
    text = path.read_text(encoding="utf-8")
    result: dict[str, str] = {}
    pattern = re.compile(r'^\s*\[("(?:\\.|[^"\\])*")]\s*=\s*("(?:\\.|[^"\\])*")\s*,?\s*$')
    # Validate the complete generated-table envelope before reading entries.
    # Comments are allowed, but no statements or trailing content are.
    meaningful = [line.strip() for line in text.splitlines()
                  if line.strip() and not line.strip().startswith("--")]
    if not meaningful or not meaningful[0].startswith("return {") or not meaningful[-1].endswith("}"):
        raise ValueError("strings.lua must contain exactly a return table")
    if meaningful[0] != "return {" and not (len(meaningful) == 1 and meaningful[0].startswith("return {") and meaningful[0].endswith("}")):
        raise ValueError("invalid strings.lua table envelope")
    # Enforce Lua table separators as a sequence: commas separate entries;
    # one trailing comma is optional, but empty/repeated commas are rejected.
    open_at, close_at = text.find("{"), text.rfind("}")
    body_for_validation = text[open_at + 1:close_at]
    body_for_validation = "\n".join(line for line in body_for_validation.splitlines()
                                      if not line.strip().startswith("--"))
    entry_pattern = re.compile(r'\[("(?:\\.|[^"\\])*")]\s*=\s*("(?:\\.|[^"\\])*")')
    matches_for_validation = list(entry_pattern.finditer(body_for_validation))
    if not matches_for_validation:
        raise ValueError("engine strings catalogue is empty")
    if body_for_validation[:matches_for_validation[0].start()].strip(" \t\r\n"):
        raise ValueError("invalid strings.lua content before first entry")
    for previous, current in zip(matches_for_validation, matches_for_validation[1:]):
        separator = body_for_validation[previous.end():current.start()]
        if not re.fullmatch(r",\s*", separator):
            raise ValueError("strings.lua entries require exactly one comma separator")
    tail = body_for_validation[matches_for_validation[-1].end():]
    if not re.fullmatch(r",?\s*", tail):
        raise ValueError("invalid strings.lua content after last entry")
    # Accept compact one-line Lua tables used by small test fixtures.
    if "return {" in text and "}" in text and len(text.splitlines()) <= 2:
        body = text[text.find("return {") + len("return {"):text.rfind("}")]
        compact = re.compile(r'\[("(?:\\.|[^"\\])*")]\s*=\s*("(?:\\.|[^"\\])*")')
        matches = list(compact.finditer(body))
        if not matches and body.strip():
            raise ValueError("invalid strings.lua directive")
        residue = compact.sub("", body).replace(",", "").strip()
        if residue:
            raise ValueError("invalid strings.lua trailing content")
        for match in matches:
            source, decoded = ast.literal_eval(match.group(1)), ast.literal_eval(match.group(2))
            if decoded != "":
                raise ValueError("engine catalogue must be a generated empty scaffold")
            if source in result:
                raise ValueError("duplicate engine source key")
            result[source] = ""
        if result:
            return result
    for line_no, line in enumerate(text.splitlines(), 1):
        stripped = line.strip()
        if not stripped or stripped.startswith("--") or stripped in {"return {", "}"}:
            continue
        match = pattern.match(line)
        if not match:
            raise ValueError(f"invalid strings.lua directive at line {line_no}")
        key, value = match.groups()
        try:
            # Lua's common escapes are sufficient for modkit output.
            source = ast.literal_eval(key)
            decoded = ast.literal_eval(value)
        except (UnicodeDecodeError, ValueError, SyntaxError) as exc:
            raise ValueError(f"invalid Lua escape at line {line_no}") from exc
        if decoded != "":
            raise ValueError(f"engine catalogue must be a generated empty scaffold (line {line_no})")
        if source in result:
            raise ValueError("duplicate engine source key")
        result[source] = ""
    if not result:
        raise ValueError(f"engine strings catalogue is empty: {path}")
    return result


def require_worksheets(root: str | Path) -> dict[str, list]:
    """Require all six ROM worksheets plus the engine strings.lua scaffold."""
    from .join import read_worksheets, WorksheetEntry
    root = Path(root)
    missing = [str(root / f"{name}.txt") for name in ROM_CATALOGS if not (root / f"{name}.txt").is_file()]
    if not (root / "strings.lua").is_file():
        missing.append(str(root / "strings.lua"))
    if missing:
        raise FileNotFoundError("required modkit catalogue(s) missing: " + ", ".join(missing))
    worksheets = read_worksheets(root)
    read_engine_catalog(root / "strings.lua")
    return worksheets


def _normal(value: str) -> str:
    return re.sub(r"\s+", " ", corpus_to_engine(value).strip()).casefold()


# Gen1Recomp ultimately calls LuaJIT's ``string.format``.  Its scanner accepts
# at most five flags, two width digits, two precision digits, and the listed
# conversion letters used by player-facing engine strings; it does not accept
# ``*``, positional arguments, or C length modifiers.  LuaJIT also has an
# internal ``%q`` extension, but it is not an engine catalogue directive.
# Keep this grammar conservative so prose such as ``100% ready`` and
# unsupported ``%q/%r`` are treated as literal text.
_PRINTF = re.compile(r"%(?:[-+ #0]{0,5}\d{0,2}(?:\.\d{0,2})?([cdisouxXeEfFgG]))")


def _printf_marker_type(directive: str) -> str:
    """Return the structural type represented by a printf directive.

    Formatting details (width, precision, length) are deliberately discarded
    for matching, while the conversion family remains part of the marker.
    This lets ``%03d`` match a corpus ``{NUM:...}``, but not a string token.
    """
    conversion = directive[-1].lower()
    if conversion in "diuox":
        return "number"
    if conversion in "aefg":
        return "number"
    if conversion == "s":
        return "string"
    if conversion == "c":
        return "char"
    return f"printf:{conversion}"


def _dynamic_marker_type(token: str) -> str | None:
    """Map a corpus runtime token to a conservative structural type."""
    if token.startswith("{NUM:"):
        return "number"
    if token == "{RAM}" or token.startswith("{RAM:"):
        return "string"
    # These are runtime substitutions containing textual names/labels.  Keep
    # them in one class: their concrete identity is not stable across games or
    # languages, whereas their ordering and string nature are stable.
    if token in {"{PLAYER}", "{RIVAL}", "{TARGET}", "{USER}", "{ID}"}:
        return "string"
    return None


def _placeholder_tokens(text: str) -> list[tuple[str, str]]:
    """Extract ordered structural placeholders from corpus or engine text."""
    converted = corpus_to_engine(text)
    result: list[tuple[str, str]] = []
    index = 0
    while index < len(converted):
        dynamic = DYNAMIC_TOKEN_RE.match(converted, index)
        if dynamic:
            marker_type = _dynamic_marker_type(dynamic.group(0))
            if marker_type:
                result.append(("dynamic", marker_type))
                index = dynamic.end()
                continue
        if converted[index:index + 2] == "%%":
            index += 2
            continue
        printf = _PRINTF.match(converted, index)
        if printf:
            directive = printf.group(0)
            result.append(("printf", directive))
            index = printf.end()
            continue
        index += 1
    return result


def _structural_form(text: str) -> str:
    """Canonical text shape with typed, ordered placeholders as markers."""
    converted = corpus_to_engine(text)
    pieces: list[str] = []
    index = 0
    while index < len(converted):
        dynamic = DYNAMIC_TOKEN_RE.match(converted, index)
        if dynamic:
            marker_type = _dynamic_marker_type(dynamic.group(0))
            if marker_type:
                pieces.append(f"\ue000{marker_type}\ue001")
                index = dynamic.end()
                continue
        if converted[index:index + 2] == "%%":
            pieces.append("%%")
            index += 2
            continue
        printf = _PRINTF.match(converted, index)
        if printf:
            pieces.append(f"\ue000{_printf_marker_type(printf.group(0))}\ue001")
            index = printf.end()
            continue
        pieces.append(converted[index])
        index += 1
    return _normal("".join(pieces))


def _structural_translation(source: str, translation: str | None) -> str | None:
    """Convert a structurally compatible corpus translation to engine text.

    A translation is accepted only when its dynamic marker sequence has the
    same arity and types as the source engine directives.  The exact source
    directives are then used in order, preserving width/precision formatting.
    """
    if translation in (None, ""):
        return None
    source_directives = [
        token for kind, token in _placeholder_tokens(source)
        if kind == "printf" and token != "%%"
    ]
    source_types = tuple(_printf_marker_type(token) for token in source_directives)
    converted = corpus_to_engine(translation)
    target_tokens = _placeholder_tokens(converted)
    target_dynamic = [token_type for kind, token_type in target_tokens if kind == "dynamic"]
    target_printf = printf_directives(converted)
    # Corpus translations normally contain dynamic tokens, not printf syntax.
    # If both are present, there is no unambiguous way to determine which
    # source directive each one denotes.
    if target_dynamic:
        if any(kind == "printf" for kind, _ in target_tokens):
            return None
        if tuple(target_dynamic) != source_types:
            return None
        pieces: list[str] = []
        index = 0
        dynamic_index = 0
        while index < len(converted):
            dynamic = DYNAMIC_TOKEN_RE.match(converted, index)
            if dynamic and _dynamic_marker_type(dynamic.group(0)):
                pieces.append(source_directives[dynamic_index])
                dynamic_index += 1
                index = dynamic.end()
                continue
            pieces.append(converted[index])
            index += 1
        converted = "".join(pieces)
    elif target_printf != printf_directives(source):
        return None
    if check_printf_directives(source, converted):
        return None
    return converted


def printf_directives(text: str) -> list[str]:
    result = []
    index = 0
    while index < len(text):
        if text[index:index + 2] == "%%":
            result.append("%%")
            index += 2
            continue
        match = _PRINTF.match(text, index)
        if match:
            result.append(match.group(0))
            index = match.end()
        else:
            index += 1
    return result


def check_printf_directives(source: str, target: str) -> list[str]:
    left, right = printf_directives(source), printf_directives(target)
    if left == right:
        return []
    return [f"printf directives mismatch: source={left!r} target={right!r}"]


def load_engine_overrides(path: str | Path | None) -> dict[str, dict]:
    if not path or not Path(path).exists():
        return {}
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("engine overrides must be a JSON object")
    if "entries" in data:
        if data.get("schema") not in (None, ENGINE_SCHEMA):
            raise ValueError("unsupported engine overrides schema")
        if data.get("version", 1) != 1:
            raise ValueError("unsupported engine overrides version")
        data = data["entries"]
    result = {}
    for source, row in data.items():
        if not isinstance(source, str) or not isinstance(row, dict) or "override" not in row:
            raise ValueError(f"invalid engine override for {source!r}")
        if not isinstance(row["override"], str) or not row["override"].strip():
            raise ValueError(f"engine override must be a non-empty string for {source!r}")
        result[source] = row
    return result


def load_semantic_anchors(path: str | Path | Mapping | None = None) -> dict[str, dict]:
    """Load conservative qid/extraction anchors (anchors contain no translations)."""
    if path is None:
        path = Path(__file__).resolve().parents[1] / "config" / "semantic_anchors.json"
    if isinstance(path, Mapping):
        data = dict(path)
    else:
        path = Path(path)
        if not path.exists():
            return {}
        data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("semantic anchors must be a JSON object")
    if "anchors" in data:
        if data.get("schema") not in (None, ANCHOR_SCHEMA):
            raise ValueError("unsupported semantic anchors schema")
        if data.get("version", 1) != 1:
            raise ValueError("unsupported semantic anchors version")
        data = data["anchors"]
    if not isinstance(data, dict):
        raise ValueError("semantic anchors anchors must be an object")

    def validate_extraction(spec: object, label: str) -> None:
        if not isinstance(spec, dict):
            raise ValueError(f"{label} extraction must be an object")
        kind = spec.get("kind", "segment")
        index = spec.get("index", 0)
        if kind not in {"segment", "token", "span", "full", "parts"}:
            raise ValueError(f"unsupported extraction kind for {label}")
        if isinstance(index, bool) or not isinstance(index, int) or index < 0:
            raise ValueError(f"invalid extraction index for {label}")
        if kind == "span" and (isinstance(spec.get("count"), bool) or not isinstance(spec.get("count"), int) or spec["count"] <= 0):
            raise ValueError(f"{label} span requires a positive count")
        if kind == "parts":
            indexes = spec.get("parts")
            separators = spec.get("separators", [])
            if (not isinstance(indexes, list) or not indexes or
                    any(isinstance(value, bool) or not isinstance(value, int) or value < 0 for value in indexes) or
                    not isinstance(separators, list) or len(separators) != len(indexes) - 1 or
                    not all(isinstance(separator, str) for separator in separators)):
                raise ValueError(f"{label} parts is malformed")
        targets = spec.get("targets", {})
        if targets is not None and not isinstance(targets, dict):
            raise ValueError(f"{label} targets must be an object")
        for language, target in (targets or {}).items():
            if not isinstance(language, str) or not language:
                raise ValueError(f"{label} target language must be non-empty")
            validate_extraction(target, f"{label} target {language!r}")

    result = {}
    for key, row in data.items():
        if not isinstance(key, str) or not isinstance(row, dict):
            raise ValueError(f"invalid semantic anchor for {key!r}")
        for field in ("source_aliases", "engine_keys", "context_keys"):
            if field in row and (not isinstance(row[field], list) or
                                 not all(isinstance(value, str) and value for value in row[field])):
                raise ValueError(f"semantic anchor {key!r} {field} must be a list of non-empty strings")
        qid = row.get("qid")
        parts = row.get("parts")
        extraction = row.get("extraction", row.get("extract"))
        if parts is not None:
            if qid is not None or extraction is not None or not isinstance(parts, list) or not parts:
                raise ValueError(f"semantic anchor {key!r} parts require a non-empty parts list")
            seen_qids = set()
            for part in parts:
                if not isinstance(part, dict) or not isinstance(part.get("qid"), str) or not part["qid"] or not isinstance(part.get("extraction"), dict):
                    raise ValueError(f"semantic anchor {key!r} parts require qid and extraction")
                validate_extraction(part["extraction"], f"semantic anchor {key!r} part")
                if part["qid"] in seen_qids:
                    raise ValueError(f"semantic anchor {key!r} parts may not repeat qids")
                seen_qids.add(part["qid"])
                if "include" in part and not isinstance(part["include"], bool):
                    raise ValueError(f"semantic anchor {key!r} part include must be boolean")
                part_kind = part["extraction"].get("kind", "segment")
                part_index = part["extraction"].get("index", 0)
                if part_kind not in {"segment", "token", "span", "full", "parts"} or isinstance(part_index, bool) or not isinstance(part_index, int) or part_index < 0:
                    raise ValueError(f"semantic anchor {key!r} has invalid part extraction")
                targets = part["extraction"].get("targets", {})
                if targets is not None and not isinstance(targets, dict):
                    raise ValueError(f"semantic anchor {key!r} part targets must be an object")
                for language, target in (targets or {}).items():
                    if not isinstance(language, str) or not isinstance(target, dict):
                        raise ValueError(f"semantic anchor {key!r} has invalid part target")
                    target_kind = target.get("kind", part_kind)
                    target_index = target.get("index", 0)
                    if target_kind not in {"segment", "token", "span", "full", "parts"} or isinstance(target_index, bool) or not isinstance(target_index, int) or target_index < 0:
                        raise ValueError(f"semantic anchor {key!r} has invalid part target extraction")
            if not isinstance(row.get("join", ""), str):
                raise ValueError(f"semantic anchor {key!r} join must be a string")
            placeholders = row.get("placeholders", {})
            if not isinstance(placeholders, dict):
                raise ValueError(f"semantic anchor {key!r} placeholders must be an object")
            for token, ref in placeholders.items():
                if not isinstance(token, str) or not token or (ref != "%s" and not (isinstance(ref, dict) and isinstance(ref.get("part"), int) and not isinstance(ref.get("part"), bool) and 0 <= ref["part"] < len(parts))):
                    raise ValueError(f"semantic anchor {key!r} has invalid placeholder mapping")
            result[key] = {**row, "parts": parts, "join": row.get("join", ""), "placeholders": placeholders}
            continue
        if not isinstance(qid, str) or not qid or not isinstance(extraction, dict):
            raise ValueError(f"semantic anchor {key!r} requires qid and extraction")
        validate_extraction(extraction, f"semantic anchor {key!r}")
        kind = extraction.get("kind", "segment")
        if kind not in {"segment", "token", "span", "full", "parts"}:
            raise ValueError(f"unsupported extraction kind for {key!r}")
        if isinstance(extraction.get("index", 0), bool) or not isinstance(extraction.get("index", 0), int) or extraction.get("index", 0) < 0:
            raise ValueError(f"invalid extraction index for {key!r}")
        if kind == "span" and (isinstance(extraction.get("count"), bool) or not isinstance(extraction.get("count"), int) or extraction["count"] <= 0):
            raise ValueError(f"semantic anchor {key!r} span requires a positive count")
        if kind == "parts":
            parts = extraction.get("parts")
            if (not isinstance(parts, list) or not parts or
                    any(isinstance(part, bool) or not isinstance(part, int) or part < 0
                        for part in parts)):
                raise ValueError(f"semantic anchor {key!r} parts requires non-negative segment indexes")
            separators = extraction.get("separators", [])
            if not isinstance(separators, list) or len(separators) != len(parts) - 1 or not all(isinstance(separator, str) for separator in separators):
                raise ValueError(f"semantic anchor {key!r} parts separators must join each segment")
        targets = extraction.get("targets", {})
        if targets is not None and not isinstance(targets, dict):
            raise ValueError(f"semantic anchor {key!r} targets must be an object")
        for language, target_extraction in (targets or {}).items():
            if not isinstance(language, str) or not isinstance(target_extraction, dict):
                raise ValueError(f"invalid semantic anchor target for {key!r}")
            target_kind = target_extraction.get("kind", kind)
            if target_kind not in {"segment", "token", "span", "full", "parts"}:
                raise ValueError(f"unsupported target extraction kind for {key!r}")
            if isinstance(target_extraction.get("index", 0), bool) or not isinstance(target_extraction.get("index", 0), int) or target_extraction.get("index", 0) < 0:
                raise ValueError(f"invalid target extraction index for {key!r}")
            if target_kind == "span" and (isinstance(target_extraction.get("count"), bool) or not isinstance(target_extraction.get("count"), int) or target_extraction["count"] <= 0):
                raise ValueError(f"semantic anchor {key!r} target span requires a positive count")
            if target_kind == "parts":
                parts = target_extraction.get("parts")
                if (not isinstance(parts, list) or not parts or
                        any(isinstance(part, bool) or not isinstance(part, int) or part < 0
                            for part in parts)):
                    raise ValueError(f"semantic anchor {key!r} target parts requires non-negative segment indexes")
                separators = target_extraction.get("separators", [])
                if not isinstance(separators, list) or len(separators) != len(parts) - 1 or not all(isinstance(separator, str) for separator in separators):
                    raise ValueError(f"semantic anchor {key!r} target parts separators must join each segment")
        result[key] = {**row, "qid": qid, "extraction": {**extraction, "kind": kind}}
    return result


def _extract_anchor(text: str, extraction: Mapping, language: str | None = None) -> str | None:
    """Extract a qid-provenanced segment/span while retaining controls.

    ``segment`` is a control-delimited unit; ``span`` is a contiguous range
    of visible whitespace tokens. Anchors may provide a language-specific
    range under ``targets`` when localizations reflow the same logical phrase;
    the selectors contain no translations.
    """
    if language and isinstance(extraction.get("targets"), Mapping):
        extraction = extraction.get("targets", {}).get(language, extraction)
    kind = extraction.get("kind", "segment")
    index = extraction.get("index", 0)
    if isinstance(index, bool) or not isinstance(index, int) or index < 0:
        return None
    if kind in {"segment", "token", "span", "parts"}:
        # RedBlue composite labels contain control bytes such as <NEXT> and
        # trailing @ markers. Controls are boundaries; punctuation in labels
        # (for example French ``ARG.``) remains part of the segment.
        converted = corpus_to_engine(text)
        converted = re.sub(r"<PK><MN>", " PKMN ", converted)
        converted = re.sub(r"<[^>]*>", " ", converted)
        # Preserve runtime placeholders as visible tokens; unknown braces are
        # controls/metadata and are not part of semantic labels.
        converted = re.sub(r"\{(?!PLAYER\}|RIVAL\}|TARGET\}|USER\}|ID\}|RAM(?:[:][^}]+)?\}|NUM:[^}]+\})[^}]*\}", " ", converted)
        converted = converted.replace("@", " ").replace("/", " ")
        # ``segment`` follows pret's control boundaries (line/paragraph/page
        # breaks), while ``token`` and ``span`` intentionally use whitespace
        # positions for composite labels whose words share one segment.
        if kind == "parts":
            parts = extraction.get("parts")
            separators = extraction.get("separators")
            if not isinstance(parts, list) or not parts or not isinstance(separators, list) or len(separators) != len(parts) - 1:
                return None
            values = [_extract_anchor(text, {"kind": "segment", "index": part}, language) for part in parts]
            if any(value is None for value in values):
                return None
            return "".join(value + (separators[index] if index < len(separators) else "")
                           for index, value in enumerate(values))
        if kind == "segment":
            segments = [part.strip() for part in re.split(r"[\n\f\v\r]+", converted) if part.strip()]
            return re.sub(r"^[/／]+|[/／]+$", "", segments[index]) if index < len(segments) else None
        matches = list(re.finditer(r"\S+", converted))
        if index >= len(matches):
            return None
        if kind in {"segment", "token"}:
            return re.sub(r"^[/／]+|[/／]+$", "", matches[index].group(0))
        count = extraction.get("count")
        if isinstance(count, bool) or not isinstance(count, int) or count <= 0 or index + count > len(matches):
            return None
        return converted[matches[index].start():matches[index + count - 1].end()]
    elif kind == "full":
        converted = corpus_to_engine(text)
        converted = re.sub(r"<[^>]*>", " ", converted).replace("@", "").replace("/", "")
        return converted.strip() or None
    else:
        return None


def match_engine_catalog(catalog: Iterable[EngineEntry | str], records: Iterable[Alignment | CorpusRecord], overrides: Mapping[str, Mapping] | None = None, semantic_anchors: str | Path | Mapping | None = None, target_lang: str | None = None) -> tuple[dict[str, str], dict]:
    """Match catalogue sources to corpus translations with auditable methods."""
    if isinstance(catalog, Mapping):
        entries = [EngineEntry(str(x)) for x in catalog.keys()]
    else:
        entries = [x if isinstance(x, EngineEntry) else EngineEntry(str(x)) for x in catalog]
    rows = list(records)
    candidates_exact: dict[str, list[tuple[str, str | None]]] = defaultdict(list)
    candidates_norm: dict[str, list[tuple[str, str | None]]] = defaultdict(list)
    candidates_structural: dict[str, list[tuple[str, str | None]]] = defaultdict(list)
    if target_lang is None:
        target_lang = next((r.target_lang for r in rows if isinstance(r, Alignment)), None)
    if target_lang is None:
        target_lang = next((r.language for r in rows if isinstance(r, CorpusRecord) and r.language != "en"), "fr")
    raw_target = [candidate for candidate in rows if isinstance(candidate, CorpusRecord) and candidate.language == target_lang]
    anchors = load_semantic_anchors(semantic_anchors)
    anchor_rows: dict[str, list[tuple[str, str | None]]] = defaultdict(list)
    for row in rows:
        if isinstance(row, Alignment) and row.qid:
            anchor_rows[row.qid].append((row.english.text, row.translation))
    raw_english = {r.qid: r for r in rows if isinstance(r, CorpusRecord) and r.language == "en" and r.qid}
    for target in raw_target:
        if target.qid and target.qid in raw_english:
            anchor_rows[target.qid].append((raw_english[target.qid].text, target.value))

    def add_candidate(source: str, translation: str | None) -> None:
        candidates_exact[corpus_to_engine(source)].append((source, translation))
        candidates_norm[_normal(source)].append((source, translation))
        candidates_structural[_structural_form(source)].append((source, translation))

    for row in rows:
        if isinstance(row, Alignment):
            source, translation = row.english.text, row.translation
        else:
            if row.language != "en":
                continue
            source, translation = row.text, row.override
            if translation is None:
                # Also accept a raw parallel CorpusRecord stream.
                by_qid = [candidate for candidate in raw_target if row.qid and candidate.qid == row.qid]
                by_english = [candidate for candidate in raw_target if candidate.english == row.text]
                # A qid match is authoritative, even when its text differs;
                # only fall back to English text when no qid candidate exists.
                french_rows = by_qid or by_english
                if french_rows:
                    for target in french_rows:
                        add_candidate(source, target.value)
                    continue
        add_candidate(source, translation)
    out: dict[str, str] = {}
    report = {"translated": 0, "total": len(entries), "auto_exact": 0, "auto_normalized": 0,
              "auto_structural": 0, "auto_semantic": 0, "fallback_english": 0,
              "override": 0, "unmatched": [], "ambiguous": {}, "details": {}, "provenance": {}}
    overrides = overrides or {}
    def anchor_for(source: str):
        anchor = anchors.get(source)
        if anchor is not None:
            return anchor
        for candidate_anchor in anchors.values():
            if source in candidate_anchor.get("engine_keys", []) or source in candidate_anchor.get("context_keys", []):
                return candidate_anchor
        return None

    def unique_anchor_row(qid: str):
        values = {(source_text, target_text) for source_text, target_text in anchor_rows.get(qid, [])
                  if source_text and target_text not in (None, "")}
        return next(iter(values)) if len(values) == 1 else None

    def resolve_parts(source: str, anchor: Mapping):
        """Compose a proven multi-qid anchor (used for split item messages)."""
        parts = anchor.get("parts", [])
        joiner = anchor.get("join", "")
        placeholders = anchor.get("placeholders", {})
        source_pieces, target_pieces = [], []
        visible_source, visible_target = [], []
        for part in parts:
            pair = unique_anchor_row(part["qid"])
            if pair is None:
                return None, set()
            extraction = part["extraction"]
            source_piece = _extract_anchor(pair[0], extraction, "en")
            target_piece = _extract_anchor(pair[1], extraction, target_lang)
            if source_piece is None or target_piece is None:
                return None, set()
            source_pieces.append(source_piece)
            target_pieces.append(target_piece)
            if part.get("include", True):
                visible_source.append(source_piece)
                visible_target.append(target_piece)

        def replace(text: str, values: list[str]) -> str:
            for token, ref in placeholders.items():
                value = "%s" if ref == "%s" else values[ref["part"]]
                text = text.replace(token, value)
            return text

        source_value = replace(joiner.join(visible_source), source_pieces)
        target_value = replace(joiner.join(visible_target), target_pieces)
        aliases = {str(alias) for alias in anchor.get("source_aliases", []) if isinstance(alias, str)}
        if source_value not in ({source} | aliases):
            return None, set()
        errors = check_printf_directives(source, target_value)
        if errors:
            return None, set()
        return corpus_to_engine(target_value), None

    def resolve_anchor(source: str, anchor: Mapping):
        if "parts" in anchor:
            return resolve_parts(source, anchor)
        extraction = anchor.get("extraction", {})
        semantic_values: set[str] = set(); semantic_error = False
        for source_text, target_text in anchor_rows.get(anchor["qid"], []):
            source_piece = _extract_anchor(source_text, extraction, "en")
            target_piece = target_text
            if source_piece is None or target_piece in (None, ""):
                semantic_error = True; continue
            target_piece = _extract_anchor(target_piece, extraction, target_lang)
            aliases = {str(alias) for alias in anchor.get("source_aliases", []) if isinstance(alias, str)}
            source_matches = (
                _normal(source_piece) == _normal(source)
                or _structural_form(source_piece) == _structural_form(source)
                or _normal(source) in {_normal(alias) for alias in aliases}
            )
            if target_piece is None or not source_matches:
                semantic_error = True; continue
            if check_printf_directives(source, target_piece) or _placeholder_tokens(source) != _placeholder_tokens(target_piece):
                semantic_error = True; continue
            semantic_values.add(corpus_to_engine(target_piece))
        if semantic_values and not semantic_error and len(semantic_values) == 1:
            return next(iter(semantic_values)), None
        if semantic_error and len(semantic_values) <= 1:
            return None, set()
        return None, semantic_values

    for entry in entries:
        source = entry.source
        if source in overrides:
            raw_value = overrides[source].get("override")
            if not isinstance(raw_value, str) or not raw_value.strip():
                raise ValueError(f"engine override must be a non-empty string for {source!r}")
            value = raw_value
            errors = check_printf_directives(source, value)
            if errors:
                raise ValueError(f"invalid engine override {source!r}: {errors[0]}")
            out[source] = value; report["override"] += 1; report["translated"] += 1
            report["details"][source] = "override"; report["provenance"][source] = {"method": "override", "target_lang": target_lang}
            continue
        declared_anchor = anchor_for(source)
        if declared_anchor is not None:
            value, anchor_values = resolve_anchor(source, declared_anchor)
            if value is not None:
                out[source] = value; report["translated"] += 1; report["auto_semantic"] += 1
                provenance = {"method": "semantic", "target_lang": target_lang}
                if "parts" in declared_anchor:
                    provenance["qids"] = [part["qid"] for part in declared_anchor["parts"]]
                else:
                    provenance.update({"qid": declared_anchor["qid"], "extraction": declared_anchor.get("extraction", {})})
                report["details"][source] = "semantic"; report["provenance"][source] = provenance
                continue
            out[source] = ""
            if anchor_values:
                report["ambiguous"][source] = sorted(anchor_values)
                report["details"][source] = "semantic_ambiguous"
                method = "semantic_ambiguous"
            else:
                report["fallback_english"] += 1
                report["unmatched"].append(source)
                report["details"][source] = "semantic_unresolved"
                method = "semantic_unresolved"
            provenance = {"method": method}
            if "parts" in declared_anchor:
                provenance["qids"] = [part["qid"] for part in declared_anchor["parts"]]
            else:
                provenance.update({"qid": declared_anchor.get("qid"), "extraction": declared_anchor.get("extraction", {})})
            report["provenance"][source] = provenance
            continue
        candidates = candidates_exact.get(corpus_to_engine(source), [])
        method = "exact"
        if not candidates:
            candidates = candidates_norm.get(_normal(source), [])
            method = "normalized"
        if not candidates:
            structural_candidates = candidates_structural.get(_structural_form(source), [])
            if structural_candidates:
                structural_values: set[str] = set()
                incompatible = False
                for _, candidate in structural_candidates:
                    if candidate in (None, ""):
                        continue
                    value = _structural_translation(source, candidate)
                    if value is None:
                        incompatible = True
                    else:
                        structural_values.add(value)
                # Never silently choose one translation when another row with
                # the same structural key is incompatible.  This protects
                # against corpus collisions and placeholder order/type drift.
                if incompatible:
                    out[source] = ""
                    report["ambiguous"][source] = sorted(structural_values)
                    report["details"][source] = "ambiguous"
                    continue
                if len(structural_values) == 1:
                    value = next(iter(structural_values))
                    out[source] = value; report["translated"] += 1; report["auto_structural"] += 1
                    report["details"][source] = "structural"
                    continue
                if len(structural_values) > 1:
                    out[source] = ""
                    report["ambiguous"][source] = sorted(structural_values)
                    report["details"][source] = "ambiguous"
                    continue
                out[source] = ""
                report["unmatched"].append(source)
                report["details"][source] = "structural_incompatible"
                continue
        values = {corpus_to_engine(v) for _, v in candidates if v not in (None, "")}
        # A semantic anchor is an explicit qid proof and may disambiguate
        # duplicate literal labels (e.g. MONEY appears in several screens).
        if len(values) == 1:
            value = next(iter(values))
            errors = check_printf_directives(source, value)
            if errors:
                raise ValueError(f"invalid engine match {source!r}: {errors[0]}")
            out[source] = value; report["translated"] += 1
            report["auto_exact" if method == "exact" else "auto_normalized"] += 1
            report["details"][source] = method
            report["provenance"][source] = {"method": method, "target_lang": target_lang}
        elif len(values) > 1:
            out[source] = ""
            report["ambiguous"][source] = sorted(values)
            report["details"][source] = "ambiguous"
        else:
            # Leave the engine scaffold empty when no target is proven. The
            # runtime naturally falls back to its English source string.
            out[source] = ""; report["fallback_english"] += 1
            report["details"][source] = "english_fallback"; report["provenance"][source] = {"method": "english_fallback", "target_lang": target_lang}
            report["unmatched"].append(source)
    report["percent"] = round(report["translated"] * 100 / report["total"], 2) if report["total"] else 100.0
    return out, report
