from __future__ import annotations

from pathlib import Path
from typing import Iterable

from .model import Alignment


def lua_string(value: str) -> str:
    value = value.replace("\\", "\\\\").replace('"', '\\"')
    value = value.replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t")
    value = value.replace("\v", "\\11").replace("\f", "\\12")
    return '"' + value + '"'


def generate_lua(items: Iterable[Alignment], output: str | Path, language: str = "fr") -> Path:
    output = Path(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    rows = [x for x in items if x.translation is not None]
    rows.sort(key=lambda x: (x.game, x.qid))
    lines = [f"-- Generated by multilingual pipeline ({language}); do not edit.", "return {"]
    for item in rows:
        lines.append(f"  [{lua_string(item.qid)}] = {lua_string(item.translation)},")
    lines.append("}")
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return output
