from __future__ import annotations

import re
from pathlib import Path
from typing import Iterable

from .model import Alignment


def reflow_for_display(text: str) -> str:
    """Replace mid-page line breaks with a space so Gen1Recomp's own
    pixel-width wrap (TextBox.paginate) lays the text edge-to-edge, instead
    of the shorter lines/CONT pauses baked into the original ROM's
    disassembly (``<LINE>``/``<CONT>``/``<NEXT>`` -> ``\\n``/``\\v``).  Page
    breaks (``\\f``, from ``<PARA>``/``<PAGE>``) are left alone: they clear
    the box and aren't a wrap concern.
    """
    text = text.replace("\n", " ").replace("\v", " ")
    text = re.sub(r" {2,}", " ", text)
    text = re.sub(r" *\f *", "\f", text)
    return text


def display_value(value: str, reflow_line_breaks: bool) -> str:
    """Apply the optional full-width reflow to a display string before it's
    Lua-escaped.  Never call this on identifiers (qids, flags, item names)."""
    return reflow_for_display(value) if reflow_line_breaks else value


def lua_string(value: str) -> str:
    value = value.replace("\\", "\\\\").replace('"', '\\"')
    value = value.replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t")
    # Pad to three digits: Lua reads \ddd greedily, so "\12" followed by a
    # digit parses as a single character. French ordinals put a digit right
    # after a page break, turning "\12" + "1er" into chr(121) + "er".
    value = value.replace("\v", "\\011").replace("\f", "\\012")
    return '"' + value + '"'


def generate_lua(items: Iterable[Alignment], output: str | Path, language: str = "fr") -> Path:
    output = Path(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    rows = [x for x in items if x.translation is not None]
    rows.sort(key=lambda x: (x.game, x.qid))
    lines = [f"-- Generated by multilingual pipeline ({language}); do not edit.", "return {"]
    for item in rows:
        lines.append(f"  [{lua_string(item.qid)}] = {lua_string(item.translation)},")
    lines.append("}")
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return output
