"""Generate a consumable Gen1Recomp translation mod and modkit worksheets."""
from __future__ import annotations

from pathlib import Path
from typing import Iterable

from .model import Alignment
from .generate import lua_string
from .join import read_worksheets, join_catalogs
from .engine import read_engine_catalog, match_engine_catalog, load_engine_overrides, require_worksheets, ROM_CATALOGS
from .corpus import canonical_language
from .project import project_version
from .literals import load_recipes, generate_handlers

CATALOGS = ("dialogue", "strings", "species_names", "move_names", "item_names", "trainer_names", "status_labels", "type_names", "demo_names")
# Keep every language at the same priority; language choice must not affect load order.
TRANSLATION_MOD_PRIORITY = 100
COMMANDS_SHOW_TEXT_KEYS = {
    "You can't carry\nany more items!",
    "{PLAYER} got\n%s!",
    "Do you want to\ngive a nickname\nto %s?",
}


def validate_commands_show_text_collisions(engine_values: dict[str, str], dialogue_keys: Iterable[str]) -> None:
    """Reject the three known Commands.show_text double-lookups before formatting."""
    keys = {str(key) for key in dialogue_keys}
    for source in COMMANDS_SHOW_TEXT_KEYS:
        value = engine_values.get(source, "")
        if value and value in keys:
            raise ValueError(
                f"Commands.show_text double lookup collision for {source!r}: "
                f"translated value {value!r} is a dialogue/Data.text key; "
                "upstream Commands.show_text API limitation"
            )


def catalog_for(qid: str) -> str:
    value = qid.lower()
    from .join import _type_name_tail, _base_qid, DEMO_NAMES_QIDS
    if _base_qid(qid) in DEMO_NAMES_QIDS.values():
        return "demo_names"
    if _type_name_tail(qid):
        return "type_names"
    if "status" in value or "condition" in value:
        return "status_labels"
    if "item" in value:
        return "item_names"
    if "move" in value or "attacknames" in value:
        return "move_names"
    if "trainer" in value or "opponent" in value:
        return "trainer_names"
    if "species" in value or "pokemon" in value or "dex" in value or "monsternames" in value:
        return "species_names"
    if qid.startswith("engine.") or "strings" in value:
        return "strings"
    return "dialogue"


def _catalog(rows: list[Alignment], title: str, language: str = "fr") -> str:
    lines = [f"-- Generated by multilingual pipeline ({language}): {title}", "return {"]
    for row in sorted(rows, key=lambda item: item.qid):
        if row.translation is not None:
            lines.append(f"  [{lua_string(row.qid)}] = {lua_string(row.translation)},")
    lines.append("}")
    return "\n".join(lines) + "\n"


MAIN = '''-- Generated translation mod; catalogs are safe to refresh.
return function(mod)
  local function catalog(name)
    local body = mod:read("lang/" .. name .. ".lua")
    if not body then return {} end
    local chunk = loadstring(body)
    if not chunk then return {} end
    local ok, value = pcall(chunk)
    return ok and type(value) == "table" and value or {}
  end
  local function each(name, apply)
    for id, value in pairs(catalog(name)) do
      if type(value) == "string" and value ~= "" then apply(id, value) end
    end
  end
  each("dialogue", function(id, value) mod.content.text:override(id, value) end)
  each("strings", function(id, value) mod.content.strings:override(id, value) end)
  each("species_names", function(id, value) mod.content.pokemon:patch(id, {name = value}) end)
  each("move_names", function(id, value) mod.content.moves:patch(id, {name = value}) end)
  each("item_names", function(id, value) mod.content.items:patch(id, {name = value}) end)
  each("trainer_names", function(id, value) mod.content.trainers:patch(id, {name = value}) end)
  each("status_labels", function(id, value) mod.content.statuses:patch(id, {label = value}) end)
  -- Type names stay English in the type_chart registry so third-party mods
  -- that key colors/UI off TypeChart.displayName keep resolving, and are
  -- localized at draw time instead: every engine site renders the type name
  -- as a standalone Font.draw string, which is substituted below.
  local okType, TypeChart = pcall(require, "src.battle.TypeChart")
  local by_english = {}
  each("type_names", function(typeId, localized)
    if okType and TypeChart and type(TypeChart.displayName) == "function" then
      local canonical = TypeChart.displayName(typeId)
      if type(canonical) == "string" and canonical ~= "" and canonical ~= localized then
        by_english[canonical] = localized
      end
    end
  end)
  if next(by_english) then
    local okFont, Font = pcall(require, "src.render.Font")
    if okFont and type(Font) == "table" then
      local function localize(text)
        if type(text) ~= "string" then return text end
        local localized = by_english[text]
        return type(localized) == "string" and localized or text
      end
      if type(Font.split) == "function" then
        local original_split = Font.split
        Font.split = function(text)
          return original_split(localize(text))
        end
      end
      if type(Font.draw) == "function" then
        local original_draw = Font.draw
        Font.draw = function(text, x, y, ...)
          return original_draw(localize(text), x, y, ...)
        end
      end
    end
  end
  -- Engine hard-coded demo-battle thrower names: the old-man tutorial's
  -- "OLD MAN" (BattleState.makeOldManDemo default) and Yellow's Pallet-intro
  -- catch demo "PROF.OAK" (data/scripts/story2.lua), shown in the translated
  -- "%s used POKé BALL!" template (BattleState.oldManThrow).  The corpus-
  -- backed demo_names catalog maps the literals per language.
  --
  -- demoName itself must stay the canonical English literal: the engine may
  -- key sprite selection off it (Yellow's Pallet intro picks Prof. Oak's
  -- sprite when demoName == "PROF.OAK"), so the translation happens only at
  -- the render site below and is reverted right after.
  local demo_names = catalog("demo_names")
  local function localizedDemoName(self, name)
    if type(name) == "string" then
      local localized = demo_names and demo_names[name]
      if type(localized) == "string" and localized ~= "" then
        return localized
      end
      if name == "PROF.OAK" then
        -- last-resort fallback: the translated trainer record
        local trainers = self and self.game and self.game.data and self.game.data.trainers
        local oak = trainers and trainers.OPP_PROF_OAK
        if oak and type(oak.name) == "string" and oak.name ~= "" then
          return oak.name
        end
      end
    end
    return nil
  end
  local okDemo, BS = pcall(require, "src.battle.BattleState")
  if okDemo and type(BS) == "table" and type(BS.oldManThrow) == "function" then
    local original_oldManThrow = BS.oldManThrow
    BS.oldManThrow = function(self, ...)
      if type(self) == "table" then
        local canonical = self.demoName
        local localized = localizedDemoName(self, canonical)
        if type(localized) == "string" and localized ~= "" then
          self.demoName = localized
          local ok, result = pcall(original_oldManThrow, self, ...)
          self.demoName = canonical
          if ok then return result end
          error(result, 0)
        end
      end
      return original_oldManThrow(self, ...)
    end
  end
  -- Note: the Pallet-intro thrower sprite is NOT overridden here — with
  -- demoName kept canonical above, the engine itself selects Prof. Oak's
  -- back pic for that demo (vanilla behavior); a player.sprite override
  -- would clobber it with the front trainer pic.
  local literal_body = mod:read("lang/literal_handlers.lua")
  if literal_body then
    local chunk, err = loadstring(literal_body, "lang/literal_handlers.lua")
    if not chunk then error(err) end
    local setup = chunk()
    if type(setup) ~= "function" then error("literal_handlers.lua must return a function") end
    setup(mod)
  end
end
'''


def generate_mod(items: Iterable[Alignment], destination: str | Path, mod_id: str = "translation-fr", language: str = "fr", modkit_worksheet: str | Path | None = None, report_path: str | Path | None = None, engine_catalog: str | Path | None = None, engine_overrides: str | Path | None = None, strict_engine: bool = False, semantic_anchors: str | Path | None = None, semantic_anchor_decisions: str | Path | None = None, target_name: str | None = None, literal_handlers: str | Path | None = None, target_description: str | None = None, engine_source: str | Path | None = None, engine_scope: str | Path | None = None) -> Path:
    """Generate a mod; ``strict_engine`` requires scaffold/catalog presence only.

    It does not require complete engine translations: unresolved entries remain
    empty and the game uses its English fallback.
    """
    language = canonical_language(language)
    destination = Path(destination); destination.mkdir(parents=True, exist_ok=True)
    rows = list(items)
    joined = None
    join_report = None
    engine_report = None
    worksheets = None
    if modkit_worksheet and strict_engine:
        require_worksheets(modkit_worksheet)
    if modkit_worksheet:
        worksheets = read_worksheets(modkit_worksheet)
        joined, join_report = join_catalogs(rows, worksheets, language)
        if engine_catalog is None and strict_engine:
            engine_catalog = Path(modkit_worksheet) / "strings.lua"
    if engine_catalog:
        from .engine_scope import forced_dynamic_keys, load_scope
        scope = load_scope(engine_scope) if engine_scope else load_scope()
        catalog = read_engine_catalog(engine_catalog)
        for key in forced_dynamic_keys(scope):
            catalog.setdefault(key, "")
        engine_values, engine_report = match_engine_catalog(catalog, rows, load_engine_overrides(engine_overrides), semantic_anchors=semantic_anchors, semantic_anchor_decisions=semantic_anchor_decisions, target_lang=language)
        for key, dynamic in scope.get("forced_dynamic_keys", {}).items():
            if key in engine_values:
                engine_report["details"][key] = "forced_dynamic"
                engine_report["provenance"][key] = {
                    **engine_report["provenance"].get(key, {}),
                    "provenance": dynamic["provenance"],
                    "reason": dynamic["reason"],
                    "callsite": dynamic["callsite"],
                    "qid": dynamic["qid"],
                }
        empty_keys = {key for key, info in scope.get("key_scope_overrides", {}).items() if info.get("engine_empty")}
        for key in empty_keys & set(engine_values):
            was_unmatched = key in engine_report.get("unmatched", [])
            if engine_values[key]:
                engine_report["translated"] -= 1
            engine_report["details"][key] = "covered_by_rom"
            engine_report["provenance"][key] = {"method": "covered-by-rom", "reason": "ROM/Data.text dialogue owns localized text"}
            engine_report["unmatched"] = [item for item in engine_report.get("unmatched", []) if item != key]
            engine_report.get("ambiguous", {}).pop(key, None)
            if was_unmatched:
                engine_report["fallback_english"] = max(0, engine_report.get("fallback_english", 0) - 1)
            engine_values[key] = ""
        engine_report["percent"] = round(engine_report["translated"] * 100 / engine_report["total"], 2) if engine_report["total"] else 100.0
        if worksheets is not None:
            validate_commands_show_text_collisions(engine_values, (entry.key for entry in worksheets.get("dialogue", ())))
    (destination / "lang").mkdir(exist_ok=True)
    for name in CATALOGS:
        if name == "strings" and engine_report is not None:
            lines = [f"-- Generated by multilingual pipeline ({language}): strings", "return {"]
            lines.extend(f"  [{lua_string(key)}] = {lua_string(value)}," for key, value in engine_values.items())
            lines.append("}")
            body = "\n".join(lines) + "\n"
        elif name == "demo_names" and joined is None:
            # Engine hard-coded demo names are qid-driven (see pipeline/join.py).
            from .join import demo_names_catalog
            values, _ = demo_names_catalog(rows, language)
            lines = [f"-- Generated by multilingual pipeline ({language}): demo_names", "return {"]
            lines.extend(f"  [{lua_string(key)}] = {lua_string(value)}," for key, value in sorted(values.items()))
            lines.append("}")
            body = "\n".join(lines) + "\n"
        elif name == "type_names" and joined is None:
            # Without a worksheet the join is purely qid-driven (see
            # pipeline/join.py); keys are the engine's type_chart ids.
            from .join import type_names_catalog
            values, _ = type_names_catalog(rows, language)
            lines = [f"-- Generated by multilingual pipeline ({language}): type_names", "return {"]
            lines.extend(f"  [{lua_string(key)}] = {lua_string(value)}," for key, value in sorted(values.items()))
            lines.append("}")
            body = "\n".join(lines) + "\n"
        elif joined is not None:
            lines = [f"-- Generated by multilingual pipeline ({language}): {name}", "return {"]
            lines.extend(f"  [{lua_string(key)}] = {lua_string(value)}," for key, value in sorted(joined[name].items()))
            lines.append("}")
            body = "\n".join(lines) + "\n"
        else:
            grouped = [row for row in rows if catalog_for(row.qid) == name]
            body = _catalog(grouped, name, language)
        (destination / "lang" / f"{name}.lua").write_text(body, encoding="utf-8")
    # Literal handlers are emitted only when every branch has a proven target
    # qid.  The runtime file is deliberately separate so an interactive build
    # can retain Modkit's scaffold main and load this optional contribution.
    literal_path = Path(literal_handlers) if literal_handlers else Path(__file__).resolve().parents[1] / "config" / "literal_handlers.json"
    runtime = destination / "lang" / "literal_handlers.lua"
    recipes = []
    generated_handlers = []
    if literal_path.is_file():
        recipes = load_recipes(literal_path)
        _, generated_handlers = generate_handlers(rows, recipes, runtime)
    elif runtime.exists():
        runtime.unlink()
    (destination / "main.lua").write_text(MAIN, encoding="utf-8")
    worksheet_root = Path(str(destination) + "-worksheet")
    worksheet_root.mkdir(parents=True, exist_ok=True)
    for name in CATALOGS:
        grouped = [row for row in rows if catalog_for(row.qid) == name]
        lines = [f"# {name} worksheet (source, not distributable)"]
        lines.extend(f"{row.qid}\t{row.english.text}" for row in sorted(grouped, key=lambda item: item.qid))
        (worksheet_root / f"{name}.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")
    import json
    display_name = target_name or f"{language} translation"
    description = target_description or (
        f"{display_name} for Pokémon Red and Blue, generated from PokeCorpus. "
        "Some special characters may not display correctly in game, and some text remains untranslated."
    )
    manifest_body = {"id": mod_id, "name": display_name, "version": project_version(), "api": 2, "entry": "main.lua", "profile": "content", "game_version": ">=0.0.0-dev <1.0.0", "category": "GAMEPLAY", "priority": TRANSLATION_MOD_PRIORITY, "dependencies": [], "optional_dependencies": [], "conflicts": [], "description": description}
    manifest = json.dumps(manifest_body, ensure_ascii=False, indent=2) + "\n"
    (destination / "manifest.json").write_text(manifest, encoding="utf-8")
    if report_path and join_report is not None:
        import json
        # A recipe is one reachable handler, regardless of how many qid
        # branches it contains.  Count qids separately for provenance; the
        # previous fixed ``* 2`` multiplier overstated coverage for flow
        # recipes and counted unavailable branches as translated.
        literal_total = len({
            (recipe.get("map"), recipe.get("text_constant"))
            for recipe in recipes if isinstance(recipe, dict)
        })
        literal_translated = len({(h.map_id, h.text_constant) for h in generated_handlers})
        def recipe_qids(handler):
            if getattr(handler, "flow_qids", ()):
                return set(handler.flow_qids)
            return {handler.prompt_qid, handler.yes_qid, handler.no_qid}
        literal_qids_total = set()
        for recipe in recipes:
            flow = recipe.get("flow") if isinstance(recipe, dict) else None
            if flow is not None:
                from .literals import _flow_qids
                try:
                    literal_qids_total.update(_flow_qids(flow))
                except ValueError:
                    continue
            else:
                for branch in ("prompt", "yes", "no"):
                    value = recipe.get(branch, {}) if isinstance(recipe, dict) else {}
                    if isinstance(value, dict) and isinstance(value.get("qid"), str):
                        literal_qids_total.add(value["qid"])
        literal_qids_translated = set().union(*(recipe_qids(handler) for handler in generated_handlers)) if generated_handlers else set()
        type_names = joined.get("type_names", {}) if joined is not None else {}
        type_names_total = len(type_names)
        type_names_translated = join_report.get("matched", {}).get("type_names", 0)
        rom_total = (sum(len(read_worksheets(modkit_worksheet)[name]) for name in ROM_CATALOGS) if modkit_worksheet else 0) + literal_total + type_names_total
        rom_translated = sum(join_report.get("matched", {}).get(name, 0) for name in ROM_CATALOGS) + literal_translated + type_names_translated
        report = dict(join_report)
        rom_details = {name: {"translated": join_report.get("matched", {}).get(name, 0), "total": len(read_worksheets(modkit_worksheet)[name])} for name in ROM_CATALOGS} if modkit_worksheet else {}
        rom_details["literal_handlers"] = {
            "translated": literal_translated, "total": literal_total,
            "qids_translated": len(literal_qids_translated),
            "qids_total": len(literal_qids_total),
        }
        rom_details["type_names"] = {
            "translated": type_names_translated, "total": type_names_total,
            "excluded": (join_report.get("type_names") or {}).get("excluded"),
        }
        demo_names = joined.get("demo_names", {}) if joined is not None else {}
        demo_names_total = len(demo_names)
        demo_names_translated = join_report.get("matched", {}).get("demo_names", 0)
        rom_total += demo_names_total
        rom_translated += demo_names_translated
        rom_details["demo_names"] = {
            "translated": demo_names_translated, "total": demo_names_total,
            "qids": (join_report.get("demo_names") or {}).get("qids"),
        }
        report["rom"] = {"translated": rom_translated, "total": rom_total, "percent": round(rom_translated * 100 / rom_total, 2) if rom_total else 100.0, "details": rom_details}
        if engine_report is not None:
            report["engine"] = engine_report
            if engine_source:
                from .engine_scope import classify_catalog, coverage_metadata, iter_callsites, validate_catalog_universe, verified_source
                source_path, _, _ = verified_source(engine_source, scope)
                validate_catalog_universe(catalog.keys(), source_path, scope)
                classified = classify_catalog(catalog.keys(), iter_callsites(source_path), scope)
                eligible = {key for key, info in classified.items() if info["eligibility"] == "eligible"}
                translated_keys = {key for key, value in engine_values.items() if isinstance(value, str) and value}
                translated = len(eligible & translated_keys)
                categories = {}
                for info in classified.values():
                    categories[info["category"]] = categories.get(info["category"], 0) + 1
                report["engine_rby"] = {
                    **coverage_metadata(scope),
                    "translated": translated,
                    "total": len(eligible),
                    "percent": round(translated * 100 / len(eligible), 2) if eligible else 100.0,
                    "eligibility": {"eligible": len(eligible), "review": sum(i["eligibility"] == "review" for i in classified.values()), "ineligible": sum(i["eligibility"] == "ineligible" for i in classified.values())},
                    "categories": categories,
                    "catalog_total": len(catalog),
                }
            else:
                report["engine_rby_warning"] = "Gen1Recomp engine source unavailable; RBY engine coverage omitted."
        Path(report_path).write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return destination
